name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'rvt-scripts'
          heroku_email: 'borolgs@gmail.com'
          usedocker: true
          docker_build_args: |
            MONGO_URI
            GITHUB_REPO
            GITHUB_USERNAME
            GUTHUB_TOKEN
            JWT_SECRET
